/* =====================================================================
 * my-shift.test.js  -  one operator's day, tested headlessly
 *
 * The day under test is not invented. It is Mei Chen's real Morning,
 * generated by running the shared engine against the demo roster, so a
 * change to the rotation moves this test rather than leaving it asserting
 * a schedule nobody runs any more.
 *
 * Three things are worth protecting here, and only one of them is about
 * drawing.
 *
 * **The screen shows one person.** Scoping happens in the route, not
 * here - but the screen must not go looking for anybody else either.
 *
 * **The breaks are drawn, not derived.** `/api/me/shift` sends turns and
 * nothing else, because the server is not allowed to compute a rotation.
 * Each turn carries `theyGoTo`, so a gap is two pushed facts laid side by
 * side. If this file ever needs to know the rotation rules to draw a
 * break, the boundary has been crossed.
 *
 * **It refuses honestly.** A manager gets a card naming them, not a
 * password box; a broken service says so; an operator with nothing
 * pushed is told that rather than shown an empty grid.
 * ===================================================================== */

"use strict";

const { test } = require("node:test");
const assert = require("node:assert");
const path = require("node:path");

const { mountMyShift } = require("./test/dom.js");

const REPO = path.resolve(__dirname, "..", "..");

/* The zone this machine is in. */
const HERE = Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";

/* ------------------------------------------------ the day, from the engine */

function meiChensMorning() {
  const g = globalThis;
  const hadWindow = "window" in g;
  g.window = g;
  require(path.join(REPO, "packages/engine/rotation-engine.js"));
  const roster = require(path.join(REPO, "packages/demo-roster/demo-roster.js"));
  const RE = g.RotationEngine;

  const plan = RE.buildPlan(
    { shift: "morning", date: "2026-08-27", blockMin: 15, stintBlocks: 3, mode: "hold" },
    roster.groups);

  const A = roster.groups[0];
  const turns = [];
  A.rigs.forEach(rigId => {
    const p = RE.rigPayload(plan, rigId);
    p.turns.forEach(t => {
      if (t.operator.id === "op-a2") {
        turns.push({
          from: t.from, to: t.to, minutes: t.minutes,
          operator: t.operator, relievedBy: t.relievedBy,
          theyGoTo: t.theyGoTo, rigId: rigId,
        });
      }
    });
  });
  turns.sort((a, b) => a.from.localeCompare(b.from));
  if (!hadWindow) delete g.window;

  return {
    operatorId: "op-a2",
    shift: { label: "Morning", date: "2026-08-27", start: "08:00", end: "16:00",
             /* This machine's own zone, so "the floor" and "this device"
                agree - the ordinary case, and the one every test below
                is about. The zone mattering at all is proved separately,
                by pushing a day from somewhere else. */
             tz: HERE, group: A.key, task: A.task },
    turns: turns,
  };
}

const DAY = meiChensMorning();

const AN_OPERATOR = {
  personAuth: "on", csrfToken: "csrf",
  account: { name: "Mei Chen", role: "operator", operatorId: "op-a2" },
};
const A_MANAGER = {
  personAuth: "on", csrfToken: "csrf",
  account: { name: "Ruth Osei", role: "manager", operatorId: null },
};
const NOBODY = { personAuth: "on", account: null, csrfToken: null };
const NO_ACCOUNTS = { personAuth: "off", account: null, csrfToken: null };

function service(who, opts) {
  opts = opts || {};
  const calls = [];
  const impl = (url, init) => {
    const p = String(url);
    calls.push({ path: p, init: init || {} });

    if (p === "/api/auth/session") {
      if (who === "unreachable") return Promise.reject(new Error("no server"));
      if (typeof who === "number") {
        return Promise.resolve({ ok: false, status: who,
          json: () => Promise.resolve({ detail: "internal error" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(who) });
    }
    if (p === "/api/me/shift") {
      if (opts.shiftStatus && opts.shiftStatus !== 200) {
        return Promise.resolve({ ok: false, status: opts.shiftStatus,
          json: () => Promise.resolve({ detail: "no" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(opts.body || DAY) });
    }
    if (p === "/api/auth/login") {
      if (opts.loginStatus && opts.loginStatus !== 200) {
        return Promise.resolve({ ok: false, status: opts.loginStatus,
          json: () => Promise.resolve({ detail: opts.loginDetail || "no" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(Object.assign(
          { name: "Mei Chen", role: "operator", operatorId: "op-a2",
            csrfToken: "csrf-from-login" }, opts.loginAs || {})) });
    }
    if (p === "/api/auth/logout") {
      return Promise.resolve({ ok: true, json: () => Promise.resolve({}) });
    }
    return Promise.reject(new Error("unexpected " + p));
  };
  impl.calls = calls;
  impl.paths = () => calls.map(c => c.path);
  return impl;
}

function mounted(who, opts, at, fn) {
  return async () => {
    const impl = service(who, opts);
    const app = await mountMyShift({ fetchImpl: impl, at: at });
    try { await fn(app, impl); } finally { app.stop(); }
  };
}

/* ------------------------------------------------------------- boot */

test("boots, and asks the page for nothing the page does not have",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.deepEqual(app.missingIds, [],
      "my-shift.js looked up ids not in index.html: " + app.missingIds.join(", "));
  }));

test("an operator sees their day",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.equal(app.showing(), "day");
  }));

/* --------------------------------------------------------- the gate */

test("nobody signed in gets the sign-in card, not a day",
  mounted(NOBODY, {}, "11:12", async app => {
    assert.equal(app.showing(), "signin");
    assert.equal(app.$("view-day").hidden, true);
  }));

test("a manager is told this screen is not theirs, and pointed at the desk",
  mounted(A_MANAGER, {}, "11:12", async app => {
    assert.equal(app.showing(), "denied");
    assert.equal(app.$("denied-name").textContent, "Ruth Osei");
  }));

test("the way out of that card actually goes to the desk",
  async () => {
    /* Asserted against the page rather than the stub: the stub knows
       about ids and nothing else, and a link it invented would prove
       nothing about the href a browser follows. */
    const fs = require("node:fs");
    const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
    const link = html.match(/id="link-desk"[^>]*/);
    assert.ok(link, "the refusal card has no way out of it");
    assert.match(html.match(/<a[^>]*id="link-desk"[^>]*>/)[0], /rotation-desk-v1/);
  });

test("a manager is not shown a password box - their password is fine",
  mounted(A_MANAGER, {}, "11:12", async app => {
    assert.equal(app.$("view-signin").hidden, true);
  }));

test("nobody's day is fetched before somebody has said who they are",
  mounted(NOBODY, {}, "11:12", async (app, impl) => {
    assert.ok(!impl.paths().includes("/api/me/shift"),
      "asked for a shift while locked: " + impl.paths().join(", "));
  }));

test("a manager's session never asks for a shift either",
  mounted(A_MANAGER, {}, "11:12", async (app, impl) => {
    assert.ok(!impl.paths().includes("/api/me/shift"));
  }));

[500, 502, 503].forEach(status => {
  test("a " + status + " from the service does not open the day",
    mounted(status, {}, "11:12", async app => {
      assert.notEqual(app.showing(), "day");
      assert.match(app.$("signin-error").textContent, /not answering/i);
    }));
});

test("with no accounts at all it says so rather than sitting blank",
  mounted(NO_ACCOUNTS, {}, "11:12", async app => {
    /* There is no operator whose shift this would be. Saying nothing is
       worse than saying that. */
    assert.equal(app.showing(), "day");
    assert.equal(app.$("empty").hidden, false);
    assert.match(app.$("empty").textContent, /no accounts configured/i);
  }));

/* ------------------------------------------------------ the timeline */

test("the day is the engine's, turn for turn",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const work = app.rows().filter(r => r.kind === "work");
    assert.equal(work.length, DAY.turns.length);
    assert.deepEqual(work.map(r => r.at), DAY.turns.map(t => t.from));
  }));

test("her morning walks across all three of the group's rigs",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* The thing no rig can answer, and the reason this screen exists. */
    const rigs = new Set(app.rows().filter(r => r.kind === "work").map(r => r.rig));
    assert.deepEqual([...rigs].sort(), ["RIG-01", "RIG-02", "RIG-03"]);
  }));

test("the gaps between turns are drawn, and named by theyGoTo",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const kinds = app.rows().map(r => r.kind);
    /* work, then whatever the outgoing turn said it goes to, alternating
       Break and Think - which is how the engine keeps the two budgets
       equal without a second rule. */
    assert.equal(kinds[0], "work");
    assert.equal(kinds[1], "Break");
    assert.equal(kinds[3], "Think");
    assert.ok(kinds.includes("Break") && kinds.includes("Think"));
  }));

test("every gap matches the theyGoTo of the turn before it",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* The boundary: this screen never decides what a gap is for. It
       reads what the desk already wrote. */
    const rows = app.rows();
    rows.forEach((row, i) => {
      if (row.kind === "work") return;
      const before = rows[i - 1];
      const turn = DAY.turns.find(t => t.from === before.at);
      assert.equal(row.kind, turn.theyGoTo,
        "a gap at " + row.at + " disagreed with the turn before it");
    });
  }));

test("no gap is drawn where there is none",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    app.rows().forEach(r => {
      assert.doesNotMatch(r.sub, /^0m/, "a zero-length rest at " + r.at);
    });
  }));

test("the budget adds up to the shift CLAUDE.md holds the floor to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const b = app.budget();
    assert.equal(b.hidden, false);
    assert.equal(b.work, "6h 00m");
    assert.equal(b.break, "1h 00m");
    assert.equal(b.think, "1h 00m");
    assert.match(b.note, /full shift/i);
  }));

/* ------------------------------------------------------------- now */

test("at 11:12 she is on RIG-02, which is where the engine puts her",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const now = app.now();
    assert.equal(now.kind, "work");
    assert.match(now.text, /RIG-02/);
    assert.match(now.text, /11:30/);
  }));

test("the countdown is to the end of the turn, in minutes and seconds",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* 11:12 to 11:30 is eighteen minutes. */
    assert.equal(app.now().left, "18:00");
  }));

test("who relieves her and where she goes are both on the now strip",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.match(app.now().text, /Tomas Rivera/);
    assert.match(app.now().text, /think/i);
  }));

test("during a break the strip says break, not a rig",
  mounted(AN_OPERATOR, {}, "08:35", async app => {
    /* 08:30-08:45 is her first break. */
    const now = app.now();
    assert.equal(now.kind, "Break");
    assert.match(now.text, /08:45/);
  }));

test("before the shift starts it counts down to the start",
  mounted(AN_OPERATOR, {}, "06:30", async app => {
    const now = app.now();
    assert.equal(now.kind, "off");
    assert.match(now.where, /starts at 08:00/);
    /* Not a bare time - how long from now, which is the thing being
       asked at 06:30. 08:00 less 06:30 is an hour and a half. */
    assert.equal(now.left, "1h 30m");
    assert.match(now.hand, /RIG-02/, "it should name the rig she starts on");
  }));

test("after the shift ends it says so, rather than counting down to nothing",
  mounted(AN_OPERATOR, {}, "17:20", async app => {
    const now = app.now();
    assert.equal(now.kind, "off");
    assert.match(now.text, /finished|done/i);
    assert.equal(now.left, "", "nothing left to count down to");
    assert.equal(app.next().hidden, true, "and nothing comes next");
  }));

test("the row happening now is marked, and the ones gone are dimmed",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const rows = app.rows();
    const now = rows.filter(r => r.isNow);
    assert.equal(now.length, 1, "exactly one row is now");
    assert.equal(now[0].at, "10:45");
    assert.ok(rows[0].isPast, "the first turn of the day should read as past");
  }));

/* --------------------------------------------------- nothing pushed */

test("an operator with nothing scheduled is told, not shown an empty grid",
  mounted(AN_OPERATOR, { body: { operatorId: "op-a2", shift: null, turns: [] } },
    "11:12", async app => {
      assert.equal(app.showing(), "day");
      assert.equal(app.$("empty").hidden, false);
      assert.match(app.$("empty").textContent, /not been pushed a schedule/i);
      assert.equal(app.rows().length, 0);
      assert.equal(app.budget().hidden, true);
    }));

test("a shift the service cannot give says so plainly",
  mounted(AN_OPERATOR, { shiftStatus: 500 }, "11:12", async app => {
    assert.match(app.$("empty").textContent, /could not reach/i);
  }));

/* ------------------------------------------------- signing in and out */

test("signing in opens the day without a reload",
  mounted(NOBODY, {}, "11:12", async app => {
    assert.equal(app.showing(), "signin");
    app.$("in-email").value = "m.chen@verlet.co";
    app.$("in-password").value = "a-real-password-12";
    app.fire(app.$("signin-form"), "submit");
    await app.settle();

    assert.equal(app.showing(), "day");
    assert.equal(app.$("who-name").textContent, "Mei Chen");
  }));

test("a manager who signs in here lands on the refusal",
  mounted(NOBODY, { loginAs: { name: "Ruth Osei", role: "manager", operatorId: null } },
    "11:12", async app => {
      app.$("in-email").value = "r.osei@verlet.co";
      app.$("in-password").value = "a-real-password-12";
      app.fire(app.$("signin-form"), "submit");
      await app.settle();
      assert.equal(app.showing(), "denied");
    }));

test("a refused sign-in says one thing, and not which half was wrong",
  mounted(NOBODY, { loginStatus: 401, loginDetail: "email or password is not right" },
    "11:12", async app => {
      app.$("in-email").value = "m.chen@verlet.co";
      app.$("in-password").value = "wrong";
      app.fire(app.$("signin-form"), "submit");
      await app.settle();

      assert.equal(app.showing(), "signin");
      assert.match(app.$("signin-error").textContent, /email or password/i);
      assert.doesNotMatch(app.$("signin-error").textContent, /no such|unknown/i);
    }));

test("being throttled says to wait rather than blaming the password",
  mounted(NOBODY, { loginStatus: 429 }, "11:12", async app => {
    app.$("in-email").value = "m.chen@verlet.co";
    app.$("in-password").value = "wrong";
    app.fire(app.$("signin-form"), "submit");
    await app.settle();
    assert.match(app.$("signin-error").textContent, /too many|wait/i);
  }));

test("signing out takes the day off the screen, not just out of view",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.ok(app.rows().length > 0);
    app.click(app.$("btn-signout"));
    await app.settle();

    assert.equal(app.showing(), "signin");
    /* Hidden is a styling instruction. This screen holds one person's
       whole day and it has to actually leave. */
    assert.equal(app.rows().length, 0);
    assert.equal(app.$("shiftline").textContent, "");
    assert.equal(app.$("who").hidden, true);
  }));

/* ------------------------------------------------ nobody else's day */

test("the screen carries nobody but the operator it belongs to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Tomas Rivera relieves her, so his name is legitimately here. What
       must not be here is anybody whose day this is not - the other
       fourteen operators on the floor. */
    const page = app.$("timeline").textContent + app.$("now").textContent
               + app.$("shiftline").textContent;
    ["Grace Okonkwo", "Sofia Lindqvist", "Lena Vogel", "Ivan Novak",
     "Yuki Tanaka", "Diego Salas"].forEach(name => {
      assert.ok(!page.includes(name), page + " mentions " + name);
    });
  }));

test("it only ever asks the service for its own shift",
  mounted(AN_OPERATOR, {}, "11:12", async (app, impl) => {
    /* No /api/state, no /api/floor/*, no per-rig schedule. This screen
       has no business knowing the floor. */
    impl.paths().forEach(p => {
      assert.ok(p === "/api/auth/session" || p === "/api/me/shift",
        "my-shift asked for " + p);
    });
  }));

/* =====================================================================
 * The redesign: what an operator can answer without reading
 *
 * The screen is read in three-second glances by somebody walking
 * between rigs. Everything below is about that: the countdown is the
 * page, the next thing is visible without scrolling, the day is drawn
 * to scale, and the hours already gone are folded away.
 * ===================================================================== */

/* ------------------------------------------------------- the clock */

test("the floor's clock is on screen, and named",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Times on this page are the floor's. An operator reading it from
       another zone has no way to know that unless it is said. */
    const c = app.clock();
    assert.equal(c.hidden, false);
    assert.equal(c.time, "11:12");
    assert.equal(c.zone, HERE);
  }));

test("the clock goes when the day does",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    app.click(app.$("btn-signout"));
    await app.settle();
    assert.equal(app.clock().hidden, true);
  }));

/* --------------------------------------------------- the countdown */

test("the countdown says what it is counting to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* A bare 18:00 is a number without a question. */
    const now = app.now();
    assert.equal(now.left, "18:00");
    assert.match(now.unit, /until you hand over/i);
  }));

test("on a break it counts to being back, not to handing over",
  mounted(AN_OPERATOR, {}, "08:35", async app => {
    const now = app.now();
    assert.equal(now.kind, "Break");
    assert.match(now.unit, /until you are back/i);
    assert.match(now.where, /break/i);
  }));

test("the bar shows how far through the turn she is",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* 10:45-11:30 is 45 minutes; at 11:12 that is 27 of them. */
    assert.equal(app.now().barWidth, "60.0%");
  }));

test("five minutes out, the hero changes state and says hand over",
  mounted(AN_OPERATOR, {}, "11:27", async app => {
    /* The rig warns before a handover. This has to as well, or an
       operator learns about it from the rig they are walking away from. */
    const now = app.now();
    assert.equal(now.kind, "soon");
    assert.match(now.label, /hand over soon/i);
    assert.equal(now.left, "3:00");
  }));

test("earlier in the same turn it is not shouting yet",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.equal(app.now().kind, "work");
    assert.match(app.now().label, /on now/i);
  }));

test("a break does not get the handover warning",
  mounted(AN_OPERATOR, {}, "08:43", async app => {
    /* Two minutes left of a break is not a handover, and dressing it as
       one would cry wolf four times a shift. */
    assert.equal(app.now().kind, "Break");
  }));

/* --------------------------------------------------------- what next */

test("what happens next is on screen without scrolling",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const next = app.next();
    assert.equal(next.hidden, false);
    assert.equal(next.kind, "Think");
    assert.match(next.sub, /11:30/);
    assert.match(next.in, /18m/);
  }));

test("next names the rig she goes back to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* The question at a handover is not "what" but "where". */
    assert.match(app.next().sub, /RIG-01/);
  }));

test("during a break, next is the rig she is walking to",
  mounted(AN_OPERATOR, {}, "08:35", async app => {
    const next = app.next();
    assert.equal(next.kind, "work");
    assert.match(next.what, /RIG-01/);
  }));

/* ----------------------------------------------------------- progress */

test("she can see how far through the shift she is",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const p = app.progress();
    assert.equal(p.hidden, false);
    assert.match(p.text, /Turn/);
    assert.match(p.text, /of 9/, "nine turns in her day");
    assert.match(p.text, /worked/);
    assert.match(p.text, /to go/);
  }));

test("progress counts the turn in progress, not just the finished ones",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* 30 + 45 + 45 behind her, plus 27 minutes of the current turn. */
    assert.match(app.progress().text, /2h 27m worked/);
  }));

/* ------------------------------------------------------ time to scale */

test("a fifteen minute break is drawn shorter than a forty-five minute turn",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Equal-height rows for unequal spans draw the wrong day, and the
       shape of the day is most of what a timeline is for. */
    const rows = app.rows();
    const work45 = rows.find(r => r.kind === "work" && r.mins === "45m");
    const break15 = rows.find(r => r.kind === "Break");
    assert.ok(parseInt(work45.height) > parseInt(break15.height),
      "45m row " + work45.height + " should be taller than 15m " + break15.height);
  }));

test("even the shortest row stays big enough to read and tap",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    app.rows().forEach(r => {
      assert.ok(parseInt(r.height) >= 46, r.at + " is only " + r.height);
    });
  }));

test("every row says how long it lasts",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    app.rows().forEach(r => assert.ok(r.mins, "no duration on the row at " + r.at));
  }));

/* -------------------------------------------------- the past, folded */

test("the hours already gone are folded away",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Opening this mid-shift should land on now, not on 08:00. */
    const rows = app.rows();
    const past = rows.filter(r => r.isPast);
    assert.ok(past.length > 0);
    assert.ok(past.every(r => r.hidden), "past rows should start folded");
    assert.ok(app.visibleRows().every(r => !r.isPast));
  }));

test("the fold says how many rows it is hiding, and opens",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const t = app.pastToggle();
    assert.equal(t.hidden, false);
    assert.match(t.text, /already done/);
    assert.equal(t.expanded, "false");

    app.click(app.$("past-toggle"));
    await app.settle();

    assert.equal(app.pastToggle().expanded, "true");
    assert.ok(app.rows().filter(r => r.isPast).every(r => !r.hidden),
      "the past should be showing once asked for");
  }));

test("at the start of a shift there is nothing to fold",
  mounted(AN_OPERATOR, {}, "08:05", async app => {
    assert.equal(app.pastToggle().hidden, true);
    assert.ok(app.visibleRows().length > 0);
  }));

/* ---------------------------------------------------------- freshness */

test("a refresh that fails keeps the day and marks it stale",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* A schedule you can still read beats an error message that
       replaced it. */
    assert.ok(app.rows().length > 0);
    assert.equal(app.$("stale").hidden, true);

    global.fetch = () => Promise.reject(new Error("network gone"));
    await app.reload();

    assert.ok(app.rows().length > 0, "the day should still be on screen");
    assert.equal(app.$("stale").hidden, false);
    assert.match(app.$("stale").textContent, /could not reach/i);
  }));

test("it says when it last heard from the service",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.match(app.$("checked").textContent, /last checked 11:12/i);
  }));

test("a schedule that changes under her says so",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Swapping somebody's day silently is how they walk to the wrong
       rig. */
    const moved = JSON.parse(JSON.stringify(DAY));
    moved.turns[3].rigId = "RIG-03";
    global.fetch = (url) => String(url) === "/api/me/shift"
      ? Promise.resolve({ ok: true, json: () => Promise.resolve(moved) })
      : Promise.reject(new Error("no"));
    await app.reload();

    assert.equal(app.$("empty").hidden, false);
    assert.match(app.$("empty").textContent, /schedule changed/i);
  }));

/* ------------------------------------------- whose clock is this, anyway
 *
 * Every time on this page is floor wall-clock, written into the payload
 * by the desk. An operator reading their shift from somewhere else - on
 * a train, at home the night before, on a floor whose machines were
 * imaged in a different zone - must be shown the floor's clock and not
 * their own. The desk had this exact bug and it is fixed in one place,
 * `minutesOnFloor()` in the shared engine; this proves this screen uses
 * it rather than reaching for `new Date()`.
 */

/* A zone some hours from this machine's, whichever machine that is. */
function elsewhere() {
  const offsetOf = tz => {
    const p = {};
    new Intl.DateTimeFormat("en-US", {
      timeZone: tz, hour12: false, hour: "2-digit", minute: "2-digit",
    }).formatToParts(new Date()).forEach(x => { p[x.type] = x.value; });
    return (+p.hour % 24) * 60 + (+p.minute);
  };
  const here = offsetOf(HERE);
  const candidates = ["Pacific/Auckland", "Asia/Tokyo", "Europe/Lisbon",
                      "America/Chicago", "Pacific/Honolulu", "UTC"];
  return candidates.find(tz => Math.abs(offsetOf(tz) - here) > 90) || null;
}

const AWAY = elsewhere();

test("the clock is the floor's, not this device's", async () => {
  if (!AWAY) return;                       // no zone far enough to tell
  const away = JSON.parse(JSON.stringify(DAY));
  away.shift.tz = AWAY;

  const app = await mountMyShift({ fetchImpl: service(AN_OPERATOR, { body: away }),
                                   at: "11:12" });
  try {
    assert.notEqual(app.clock().time, "11:12",
      "this device says 11:12; on that floor it does not, so the page "
      + "showed its own clock instead of the floor's");
    assert.equal(app.clock().zone, AWAY,
      "and it should say which floor's clock it is showing");
  } finally { app.stop(); }
});

test("a phone in the same building as the floor is unchanged", async () => {
  /* The normal case, and the reason a zone bug goes unnoticed. */
  const app = await mountMyShift({ fetchImpl: service(AN_OPERATOR, {}), at: "11:12" });
  try {
    assert.equal(app.clock().time, "11:12");
  } finally { app.stop(); }
});

test("which turn is 'now' follows the floor's clock too", async () => {
  if (!AWAY) return;
  const away = JSON.parse(JSON.stringify(DAY));
  away.shift.tz = AWAY;

  const here = await mountMyShift({ fetchImpl: service(AN_OPERATOR, {}), at: "11:12" });
  const hereNow = here.rows().find(r => r.isNow);
  here.stop();

  const there = await mountMyShift({ fetchImpl: service(AN_OPERATOR, { body: away }),
                                     at: "11:12" });
  const thereNow = there.rows().find(r => r.isNow);
  there.stop();

  /* Being told you are mid-turn when the floor has not started is worse
     than a wrong clock - it is a wrong answer to "am I late". */
  assert.notDeepEqual(
    hereNow ? hereNow.at : null,
    thereNow ? thereNow.at : null,
    "the same instant picked the same turn in two different zones");
});

/* ------------------------------------------- the one thing headless misses
 *
 * `hidden` is a property to a DOM stub and a stylesheet rule to a
 * browser. Every class on this page that sets `display: flex` outranks
 * the browser's built-in `[hidden] { display: none }`, so an element
 * told to hide draws anyway - as an empty sliver, or worse, as a whole
 * second screen stacked under the first.
 *
 * The desk hit this and wrote it down; this page reintroduced it and it
 * took a browser to see. No stub can catch it, so what is asserted here
 * is that the rule which fixes it is still in the stylesheet.
 */

test("the stylesheet makes `hidden` actually hide", () => {
  const fs = require("node:fs");
  const css = fs.readFileSync(
    path.join(__dirname, "assets/my-shift.css"), "utf8");

  assert.match(css, /\[hidden\]\s*\{[^}]*display:\s*none\s*!important/,
    "without this rule every element hidden by attribute still paints, "
    + "and no test in this file can tell");
});

test("every element this page hides by attribute is covered by that rule", () => {
  const fs = require("node:fs");
  const js = fs.readFileSync(path.join(__dirname, "assets/my-shift.js"), "utf8");
  const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");

  /* Anything the script toggles, plus anything shipped hidden. */
  const toggled = new Set();
  (js.match(/\$\("([a-z-]+)"\)\.hidden\s*=/g) || [])
    .forEach(m => toggled.add(m.match(/\$\("([a-z-]+)"\)/)[1]));
  (html.match(/id="([a-z-]+)"[^>]*\shidden/g) || [])
    .forEach(m => toggled.add(m.match(/id="([a-z-]+)"/)[1]));

  assert.ok(toggled.size >= 6,
    "expected several hidden-toggled elements, found " + [...toggled].join(", "));

  /* The global rule covers all of them by construction - this asserts
     nobody has since narrowed it to a specific selector. */
  const css = fs.readFileSync(path.join(__dirname, "assets/my-shift.css"), "utf8");
  const rule = css.match(/^\[hidden\]\s*\{[^}]*\}/m);
  assert.ok(rule, "the rule is no longer global; " + toggled.size
    + " elements rely on it: " + [...toggled].sort().join(", "));
});
