/* =====================================================================
 * my-shift.test.js  -  one operator's day, tested headlessly
 *
 * The day under test is not invented. It is Mei Chen's real Morning,
 * generated by running the shared engine against the demo roster, so a
 * change to the rotation moves this test rather than leaving it asserting
 * a schedule nobody runs any more.
 *
 * Three things are worth protecting here, and only one of them is about
 * drawing.
 *
 * **The screen shows one person.** Scoping happens in the route, not
 * here - but the screen must not go looking for anybody else either.
 *
 * **The breaks are drawn, not derived.** `/api/me/shift` sends turns and
 * nothing else, because the server is not allowed to compute a rotation.
 * Each turn carries `theyGoTo`, so a gap is two pushed facts laid side by
 * side. If this file ever needs to know the rotation rules to draw a
 * break, the boundary has been crossed.
 *
 * **It refuses honestly.** A manager gets a card naming them, not a
 * password box; a broken service says so; an operator with nothing
 * pushed is told that rather than shown an empty grid.
 * ===================================================================== */

"use strict";

const { test } = require("node:test");
const assert = require("node:assert");
const path = require("node:path");

const { mountMyShift } = require("./test/dom.js");

const REPO = path.resolve(__dirname, "..", "..");

/* ------------------------------------------------ the day, from the engine */

function meiChensMorning() {
  const g = globalThis;
  const hadWindow = "window" in g;
  g.window = g;
  require(path.join(REPO, "packages/engine/rotation-engine.js"));
  const roster = require(path.join(REPO, "packages/demo-roster/demo-roster.js"));
  const RE = g.RotationEngine;

  const plan = RE.buildPlan(
    { shift: "morning", date: "2026-08-27", blockMin: 15, stintBlocks: 3, mode: "hold" },
    roster.groups);

  const A = roster.groups[0];
  const turns = [];
  A.rigs.forEach(rigId => {
    const p = RE.rigPayload(plan, rigId);
    p.turns.forEach(t => {
      if (t.operator.id === "op-a2") {
        turns.push({
          from: t.from, to: t.to, minutes: t.minutes,
          operator: t.operator, relievedBy: t.relievedBy,
          theyGoTo: t.theyGoTo, rigId: rigId,
        });
      }
    });
  });
  turns.sort((a, b) => a.from.localeCompare(b.from));
  if (!hadWindow) delete g.window;

  return {
    operatorId: "op-a2",
    shift: { label: "Morning", date: "2026-08-27", start: "08:00", end: "16:00",
             tz: "UTC", group: A.key, task: A.task },
    turns: turns,
  };
}

const DAY = meiChensMorning();

const AN_OPERATOR = {
  personAuth: "on", csrfToken: "csrf",
  account: { name: "Mei Chen", role: "operator", operatorId: "op-a2" },
};
const A_MANAGER = {
  personAuth: "on", csrfToken: "csrf",
  account: { name: "Ruth Osei", role: "manager", operatorId: null },
};
const NOBODY = { personAuth: "on", account: null, csrfToken: null };
const NO_ACCOUNTS = { personAuth: "off", account: null, csrfToken: null };

function service(who, opts) {
  opts = opts || {};
  const calls = [];
  const impl = (url, init) => {
    const p = String(url);
    calls.push({ path: p, init: init || {} });

    if (p === "/api/auth/session") {
      if (who === "unreachable") return Promise.reject(new Error("no server"));
      if (typeof who === "number") {
        return Promise.resolve({ ok: false, status: who,
          json: () => Promise.resolve({ detail: "internal error" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(who) });
    }
    if (p === "/api/me/shift") {
      if (opts.shiftStatus && opts.shiftStatus !== 200) {
        return Promise.resolve({ ok: false, status: opts.shiftStatus,
          json: () => Promise.resolve({ detail: "no" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(opts.body || DAY) });
    }
    if (p === "/api/auth/login") {
      if (opts.loginStatus && opts.loginStatus !== 200) {
        return Promise.resolve({ ok: false, status: opts.loginStatus,
          json: () => Promise.resolve({ detail: opts.loginDetail || "no" }) });
      }
      return Promise.resolve({ ok: true, status: 200,
        json: () => Promise.resolve(Object.assign(
          { name: "Mei Chen", role: "operator", operatorId: "op-a2",
            csrfToken: "csrf-from-login" }, opts.loginAs || {})) });
    }
    if (p === "/api/auth/logout") {
      return Promise.resolve({ ok: true, json: () => Promise.resolve({}) });
    }
    return Promise.reject(new Error("unexpected " + p));
  };
  impl.calls = calls;
  impl.paths = () => calls.map(c => c.path);
  return impl;
}

function mounted(who, opts, at, fn) {
  return async () => {
    const impl = service(who, opts);
    const app = await mountMyShift({ fetchImpl: impl, at: at });
    try { await fn(app, impl); } finally { app.stop(); }
  };
}

/* ------------------------------------------------------------- boot */

test("boots, and asks the page for nothing the page does not have",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.deepEqual(app.missingIds, [],
      "my-shift.js looked up ids not in index.html: " + app.missingIds.join(", "));
  }));

test("an operator sees their day",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.equal(app.showing(), "day");
  }));

/* --------------------------------------------------------- the gate */

test("nobody signed in gets the sign-in card, not a day",
  mounted(NOBODY, {}, "11:12", async app => {
    assert.equal(app.showing(), "signin");
    assert.equal(app.$("view-day").hidden, true);
  }));

test("a manager is told this screen is not theirs, and pointed at the desk",
  mounted(A_MANAGER, {}, "11:12", async app => {
    assert.equal(app.showing(), "denied");
    assert.equal(app.$("denied-name").textContent, "Ruth Osei");
  }));

test("the way out of that card actually goes to the desk",
  async () => {
    /* Asserted against the page rather than the stub: the stub knows
       about ids and nothing else, and a link it invented would prove
       nothing about the href a browser follows. */
    const fs = require("node:fs");
    const html = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
    const link = html.match(/id="link-desk"[^>]*/);
    assert.ok(link, "the refusal card has no way out of it");
    assert.match(html.match(/<a[^>]*id="link-desk"[^>]*>/)[0], /rotation-desk-v1/);
  });

test("a manager is not shown a password box - their password is fine",
  mounted(A_MANAGER, {}, "11:12", async app => {
    assert.equal(app.$("view-signin").hidden, true);
  }));

test("nobody's day is fetched before somebody has said who they are",
  mounted(NOBODY, {}, "11:12", async (app, impl) => {
    assert.ok(!impl.paths().includes("/api/me/shift"),
      "asked for a shift while locked: " + impl.paths().join(", "));
  }));

test("a manager's session never asks for a shift either",
  mounted(A_MANAGER, {}, "11:12", async (app, impl) => {
    assert.ok(!impl.paths().includes("/api/me/shift"));
  }));

[500, 502, 503].forEach(status => {
  test("a " + status + " from the service does not open the day",
    mounted(status, {}, "11:12", async app => {
      assert.notEqual(app.showing(), "day");
      assert.match(app.$("signin-error").textContent, /not answering/i);
    }));
});

test("with no accounts at all it says so rather than sitting blank",
  mounted(NO_ACCOUNTS, {}, "11:12", async app => {
    /* There is no operator whose shift this would be. Saying nothing is
       worse than saying that. */
    assert.equal(app.showing(), "day");
    assert.equal(app.$("empty").hidden, false);
    assert.match(app.$("empty").textContent, /no accounts configured/i);
  }));

/* ------------------------------------------------------ the timeline */

test("the day is the engine's, turn for turn",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const work = app.rows().filter(r => r.kind === "work");
    assert.equal(work.length, DAY.turns.length);
    assert.deepEqual(work.map(r => r.at), DAY.turns.map(t => t.from));
  }));

test("her morning walks across all three of the group's rigs",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* The thing no rig can answer, and the reason this screen exists. */
    const rigs = new Set(app.rows().filter(r => r.kind === "work")
      .map(r => r.what.replace("Work ", "")));
    assert.deepEqual([...rigs].sort(), ["RIG-01", "RIG-02", "RIG-03"]);
  }));

test("the gaps between turns are drawn, and named by theyGoTo",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const kinds = app.rows().map(r => r.kind);
    /* work, then whatever the outgoing turn said it goes to, alternating
       Break and Think - which is how the engine keeps the two budgets
       equal without a second rule. */
    assert.equal(kinds[0], "work");
    assert.equal(kinds[1], "Break");
    assert.equal(kinds[3], "Think");
    assert.ok(kinds.includes("Break") && kinds.includes("Think"));
  }));

test("every gap matches the theyGoTo of the turn before it",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* The boundary: this screen never decides what a gap is for. It
       reads what the desk already wrote. */
    const rows = app.rows();
    rows.forEach((row, i) => {
      if (row.kind === "work") return;
      const before = rows[i - 1];
      const turn = DAY.turns.find(t => t.from === before.at);
      assert.equal(row.kind, turn.theyGoTo,
        "a gap at " + row.at + " disagreed with the turn before it");
    });
  }));

test("no gap is drawn where there is none",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    app.rows().forEach(r => {
      assert.doesNotMatch(r.sub, /^0m/, "a zero-length rest at " + r.at);
    });
  }));

test("the budget adds up to the shift CLAUDE.md holds the floor to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const b = app.budget();
    assert.equal(b.hidden, false);
    assert.equal(b.work, "6h 00m");
    assert.equal(b.break, "1h 00m");
    assert.equal(b.think, "1h 00m");
    assert.match(b.note, /full shift/i);
  }));

/* ------------------------------------------------------------- now */

test("at 11:12 she is on RIG-02, which is where the engine puts her",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const now = app.now();
    assert.equal(now.kind, "work");
    assert.match(now.text, /RIG-02/);
    assert.match(now.text, /11:30/);
  }));

test("the countdown is to the end of the turn, in minutes and seconds",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* 11:12 to 11:30 is eighteen minutes. */
    assert.equal(app.now().left, "18:00");
  }));

test("who relieves her and where she goes are both on the now strip",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.match(app.now().text, /Tomas Rivera/);
    assert.match(app.now().text, /think/i);
  }));

test("during a break the strip says break, not a rig",
  mounted(AN_OPERATOR, {}, "08:35", async app => {
    /* 08:30-08:45 is her first break. */
    const now = app.now();
    assert.equal(now.kind, "Break");
    assert.match(now.text, /08:45/);
  }));

test("before the shift starts it says when it starts",
  mounted(AN_OPERATOR, {}, "06:30", async app => {
    assert.equal(app.now().kind, null);
    assert.match(app.now().text, /starts at 08:00/);
  }));

test("after the shift ends it says so, rather than counting down to nothing",
  mounted(AN_OPERATOR, {}, "17:20", async app => {
    assert.equal(app.now().kind, null);
    assert.match(app.now().text, /finished/i);
  }));

test("the row happening now is marked, and the ones gone are dimmed",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    const rows = app.rows();
    const now = rows.filter(r => r.isNow);
    assert.equal(now.length, 1, "exactly one row is now");
    assert.equal(now[0].at, "10:45");
    assert.ok(rows[0].isPast, "the first turn of the day should read as past");
  }));

/* --------------------------------------------------- nothing pushed */

test("an operator with nothing scheduled is told, not shown an empty grid",
  mounted(AN_OPERATOR, { body: { operatorId: "op-a2", shift: null, turns: [] } },
    "11:12", async app => {
      assert.equal(app.showing(), "day");
      assert.equal(app.$("empty").hidden, false);
      assert.match(app.$("empty").textContent, /not been pushed a schedule/i);
      assert.equal(app.rows().length, 0);
      assert.equal(app.budget().hidden, true);
    }));

test("a shift the service cannot give says so plainly",
  mounted(AN_OPERATOR, { shiftStatus: 500 }, "11:12", async app => {
    assert.match(app.$("empty").textContent, /could not reach/i);
  }));

/* ------------------------------------------------- signing in and out */

test("signing in opens the day without a reload",
  mounted(NOBODY, {}, "11:12", async app => {
    assert.equal(app.showing(), "signin");
    app.$("in-email").value = "m.chen@verlet.co";
    app.$("in-password").value = "a-real-password-12";
    app.fire(app.$("signin-form"), "submit");
    await app.settle();

    assert.equal(app.showing(), "day");
    assert.equal(app.$("who-name").textContent, "Mei Chen");
  }));

test("a manager who signs in here lands on the refusal",
  mounted(NOBODY, { loginAs: { name: "Ruth Osei", role: "manager", operatorId: null } },
    "11:12", async app => {
      app.$("in-email").value = "r.osei@verlet.co";
      app.$("in-password").value = "a-real-password-12";
      app.fire(app.$("signin-form"), "submit");
      await app.settle();
      assert.equal(app.showing(), "denied");
    }));

test("a refused sign-in says one thing, and not which half was wrong",
  mounted(NOBODY, { loginStatus: 401, loginDetail: "email or password is not right" },
    "11:12", async app => {
      app.$("in-email").value = "m.chen@verlet.co";
      app.$("in-password").value = "wrong";
      app.fire(app.$("signin-form"), "submit");
      await app.settle();

      assert.equal(app.showing(), "signin");
      assert.match(app.$("signin-error").textContent, /email or password/i);
      assert.doesNotMatch(app.$("signin-error").textContent, /no such|unknown/i);
    }));

test("being throttled says to wait rather than blaming the password",
  mounted(NOBODY, { loginStatus: 429 }, "11:12", async app => {
    app.$("in-email").value = "m.chen@verlet.co";
    app.$("in-password").value = "wrong";
    app.fire(app.$("signin-form"), "submit");
    await app.settle();
    assert.match(app.$("signin-error").textContent, /too many|wait/i);
  }));

test("signing out takes the day off the screen, not just out of view",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    assert.ok(app.rows().length > 0);
    app.click(app.$("btn-signout"));
    await app.settle();

    assert.equal(app.showing(), "signin");
    /* Hidden is a styling instruction. This screen holds one person's
       whole day and it has to actually leave. */
    assert.equal(app.rows().length, 0);
    assert.equal(app.$("shiftline").textContent, "");
    assert.equal(app.$("who").hidden, true);
  }));

/* ------------------------------------------------ nobody else's day */

test("the screen carries nobody but the operator it belongs to",
  mounted(AN_OPERATOR, {}, "11:12", async app => {
    /* Tomas Rivera relieves her, so his name is legitimately here. What
       must not be here is anybody whose day this is not - the other
       fourteen operators on the floor. */
    const page = app.$("timeline").textContent + app.$("now").textContent
               + app.$("shiftline").textContent;
    ["Grace Okonkwo", "Sofia Lindqvist", "Lena Vogel", "Ivan Novak",
     "Yuki Tanaka", "Diego Salas"].forEach(name => {
      assert.ok(!page.includes(name), page + " mentions " + name);
    });
  }));

test("it only ever asks the service for its own shift",
  mounted(AN_OPERATOR, {}, "11:12", async (app, impl) => {
    /* No /api/state, no /api/floor/*, no per-rig schedule. This screen
       has no business knowing the floor. */
    impl.paths().forEach(p => {
      assert.ok(p === "/api/auth/session" || p === "/api/me/shift",
        "my-shift asked for " + p);
    });
  }));
