// Declaring the app's own commands to the ACL, so a capability can name
// them.
//
// A page served by the floor is a *remote* origin, and tauri refuses
// remote content every custom command unless a capability explicitly
// allows it. Capabilities grant permissions by identifier, and an app's
// own commands have none until this manifest exists - so without it
// there is nothing for `bridge::allow_remote` to ask for.
//
// `commands()` autogenerates an `allow-<name>` permission per command
// into `permissions/autogenerated`, which is build output rather than
// source and is ignored by git.
//
// The trade this makes, worth knowing: declaring an app manifest turns
// the ACL on for *local* pages too, where before it was implicit. That
// is why the capability in `bridge.rs` is added whether or not RIG_URL
// is set - the bundled fallback page would otherwise be refused the same
// commands, and the failure would only appear if it ever used them.

include!("src/command_names.rs");

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("the rig shell's build script could not describe its commands");
}
