"""people, not just machines

The desk had no way to know who was using it. `accounts` and
`account_sessions` are that, and nothing on the rig's path changes: a rig
still authenticates as a machine with a per-rig bearer token and the
operator standing at it still authenticates nothing.

Both tables are new and empty, so the indexes below are built inline. The
README's warning about `CREATE INDEX` locking `rig_events` against twelve
writing rigs does not apply to a table that has never had a row in it.

Revision ID: 26aee232ddc7
Revises: 442e8677a7ff
"""
from alembic import op
import sqlalchemy as sa


revision = '26aee232ddc7'
down_revision = '442e8677a7ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'manager' AND operator_id IS NULL) OR (role = 'operator' AND operator_id IS NOT NULL)", name='ck_accounts_operator_id_matches_role'),
    sa.CheckConstraint("role IN ('manager', 'operator')", name='ck_accounts_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_accounts_email', 'accounts', ['email'], unique=True)
    op.create_index('uq_accounts_operator', 'accounts', ['operator_id'], unique=True, postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.create_table('account_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_sessions_expires', 'account_sessions', ['expires_at'], unique=False)
    op.create_index('uq_account_sessions_fingerprint', 'account_sessions', ['token_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_account_sessions_fingerprint', table_name='account_sessions')
    op.drop_index('ix_account_sessions_expires', table_name='account_sessions')
    op.drop_table('account_sessions')
    op.drop_index('uq_accounts_operator', table_name='accounts', postgresql_where=sa.text('operator_id IS NOT NULL'))
    op.drop_index('uq_accounts_email', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
