"""episode video state

Revision ID: 2ad33b63b7b7
Revises: 6f76e266dbfb
"""
from alembic import op
import sqlalchemy as sa


revision = '2ad33b63b7b7'
down_revision = '6f76e266dbfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('video_state', sa.String(length=16), server_default='pending', nullable=False))
    op.add_column('episodes', sa.Column('video_key', sa.Text(), nullable=True))
    op.add_column('episodes', sa.Column('video_bytes', sa.BigInteger(), nullable=True))
    op.add_column('episodes', sa.Column('video_sha256', sa.String(length=64), nullable=True))
    op.add_column('episodes', sa.Column('video_stored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('episodes', sa.Column('video_archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_episodes_video_state', 'episodes', ['video_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episodes_video_state', table_name='episodes')
    op.drop_column('episodes', 'video_archived_at')
    op.drop_column('episodes', 'video_stored_at')
    op.drop_column('episodes', 'video_sha256')
    op.drop_column('episodes', 'video_bytes')
    op.drop_column('episodes', 'video_key')
    op.drop_column('episodes', 'video_state')
    # ### end Alembic commands ###
