"""a push covers the whole day

Revision ID: 442e8677a7ff
Revises: e8a71c919b40
"""
from alembic import op
import sqlalchemy as sa


revision = '442e8677a7ff'
down_revision = 'e8a71c919b40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_schedules_push_rig'), 'schedules', type_='unique')
    op.create_unique_constraint('uq_schedules_push_rig_shift', 'schedules', ['push_id', 'rig_id', 'shift_date', 'shift_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_schedules_push_rig_shift', 'schedules', type_='unique')
    op.create_unique_constraint(op.f('uq_schedules_push_rig'), 'schedules', ['push_id', 'rig_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
