"""video is per camera

A take is three cameras. `object_key()` has always produced three keys -
front, wrist-l, overhead - but the bookkeeping was six columns on
`episodes` with a single `video_key`, so `confirm()` overwrote it with
whichever camera landed last.

That hid itself for as long as nothing ever deleted anything. The moment
the drain started freeing the spool it became visible on disk: one camera
per take archived and released, the other two left behind for ever,
uncounted by the very backlog meant to notice a spool filling up. And
`/floor/video` - the measurement that exists to replace the plan's sizing
guess - was reporting a third of the truth.

The rows are backfilled, not discarded. The camera is recovered from the
key, which has always carried it: `RIG-03/<episode>/front.mp4`. Rows with
no key at all were never uploaded and get no row, which is correct -
`pending` has to keep meaning "we are waiting for this".

The two thirds already orphaned on disk are not recoverable from the
database, because nothing ever recorded them. They are stale files under
the spool root and can be deleted by hand; every take from here on is
accounted for.

Revision ID: 4475469fc762
Revises: e6747a3617c6
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4475469fc762'
down_revision = 'e6747a3617c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_videos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('camera', sa.String(length=32), nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.episode_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'camera', name='uq_episode_videos_camera')
    )
    op.create_index('ix_episode_videos_rig', 'episode_videos', ['rig_id'], unique=False)
    op.create_index('ix_episode_videos_state', 'episode_videos', ['state'], unique=False)
    op.create_index('ix_episode_videos_unfreed', 'episode_videos', ['archived_at'], unique=False, postgresql_where=sa.text('freed_at IS NULL'))
    # Move what is there before dropping where it lived. The camera is
    # recovered from the key: 'RIG-03/<episode>/front.mp4' -> 'front'.
    op.execute(sa.text(r"""
        INSERT INTO episode_videos
            (episode_id, camera, rig_id, state, key, bytes, sha256,
             stored_at, archived_at, freed_at)
        SELECT e.episode_id,
               regexp_replace(split_part(e.video_key, '/', 3), '\.mp4$', ''),
               e.rig_id, e.video_state, e.video_key, e.video_bytes,
               e.video_sha256, e.video_stored_at, e.video_archived_at,
               e.video_freed_at
        FROM episodes e
        WHERE e.video_key IS NOT NULL
          AND split_part(e.video_key, '/', 3) <> ''
        ON CONFLICT (episode_id, camera) DO NOTHING
    """))

    op.drop_index(op.f('ix_episodes_unfreed'), table_name='episodes', postgresql_where='(video_freed_at IS NULL)')
    op.drop_index(op.f('ix_episodes_video_state'), table_name='episodes')
    op.drop_column('episodes', 'video_stored_at')
    op.drop_column('episodes', 'video_state')
    op.drop_column('episodes', 'video_freed_at')
    op.drop_column('episodes', 'video_bytes')
    op.drop_column('episodes', 'video_key')
    op.drop_column('episodes', 'video_sha256')
    op.drop_column('episodes', 'video_archived_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('video_archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('video_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('video_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('video_bytes', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('video_freed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('video_state', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('episodes', sa.Column('video_stored_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_episodes_video_state'), 'episodes', ['video_state'], unique=False)
    op.create_index(op.f('ix_episodes_unfreed'), 'episodes', ['video_archived_at'], unique=False, postgresql_where='(video_freed_at IS NULL)')
    op.drop_index('ix_episode_videos_unfreed', table_name='episode_videos', postgresql_where=sa.text('freed_at IS NULL'))
    op.drop_index('ix_episode_videos_state', table_name='episode_videos')
    op.drop_index('ix_episode_videos_rig', table_name='episode_videos')
    op.drop_table('episode_videos')
    # ### end Alembic commands ###
