"""ledger and schedules

Revision ID: 5447b9c9547e
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5447b9c9547e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rig_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('bucket', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('push_id', sa.UUID(), nullable=True),
    sa.Column('projected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rig_id', 'event_id', name='uq_rig_events_rig_event')
    )
    op.create_index('ix_rig_events_rig_seq', 'rig_events', ['rig_id', 'seq'], unique=False)
    op.create_index('ix_rig_events_unprojected', 'rig_events', ['projected_at'], unique=False, postgresql_where=sa.text('projected_at IS NULL'))
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('push_id', sa.UUID(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_id', 'rig_id', name='uq_schedules_push_rig')
    )
    op.create_index('ix_schedules_rig_shift', 'schedules', ['rig_id', 'shift_date', 'shift_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedules_rig_shift', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('ix_rig_events_unprojected', table_name='rig_events', postgresql_where=sa.text('projected_at IS NULL'))
    op.drop_index('ix_rig_events_rig_seq', table_name='rig_events')
    op.drop_table('rig_events')
    # ### end Alembic commands ###
