"""floor status and alerts

Revision ID: 6f76e266dbfb
Revises: 9281c0db8f39
"""
from alembic import op
import sqlalchemy as sa


revision = '6f76e266dbfb'
down_revision = '9281c0db8f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'opened_at', name='uq_alerts_key_opened')
    )
    op.create_index('ix_alerts_open', 'alerts', ['resolved_at'], unique=False)
    op.create_index('uq_alerts_open_key', 'alerts', ['key'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('rig_status',
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rig_clock_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skew_secs', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('rig_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rig_status')
    op.drop_index('uq_alerts_open_key', table_name='alerts', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index('ix_alerts_open', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
