"""a way back in for a forgotten password

One table, shaped like `account_sessions` next to it and for the same
reasons: a fingerprint of the token rather than the token, so a dump of
this is a list of expiry dates instead of a set of working ways in; and a
row rather than a signed value, so it can be withdrawn.

Withdrawal is not optional here. A reset token is the account for as long
as it lives, so it has to be single-use and short-lived - `used_at` and
`expires_at` are those two properties, and the unique index on the
fingerprint is what lets `UPDATE ... WHERE used_at IS NULL` decide a race
in the database rather than in the application.

`ON DELETE CASCADE`: a deleted account must not leave a live way into
the account it no longer is.

Revision ID: 73909a57ffda
Revises: 7d8934168889
"""
from alembic import op
import sqlalchemy as sa


revision = '73909a57ffda'
down_revision = '7d8934168889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_from', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_resets_account', 'password_resets', ['account_id'], unique=False)
    op.create_index('ix_password_resets_expires', 'password_resets', ['expires_at'], unique=False)
    op.create_index('uq_password_resets_fingerprint', 'password_resets', ['token_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_password_resets_fingerprint', table_name='password_resets')
    op.drop_index('ix_password_resets_expires', table_name='password_resets')
    op.drop_index('ix_password_resets_account', table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
