"""who changed the floors day

Revision ID: 7d8934168889
Revises: 26aee232ddc7
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '7d8934168889'
down_revision = '26aee232ddc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_pushes',
    sa.Column('push_id', sa.UUID(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('covered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('push_id')
    )
    op.create_index('ix_schedule_pushes_at', 'schedule_pushes', ['pushed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_pushes_at', table_name='schedule_pushes')
    op.drop_table('schedule_pushes')
    # ### end Alembic commands ###
