"""fact domains

Revision ID: 9281c0db8f39
Revises: 5447b9c9547e
"""
from alembic import op
import sqlalchemy as sa


revision = '9281c0db8f39'
down_revision = '5447b9c9547e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_secs', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('source_event', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('episode_id')
    )
    op.create_index('ix_episodes_operator', 'episodes', ['operator_id'], unique=False)
    op.create_index('ix_episodes_rig_shift', 'episodes', ['rig_id', 'shift_date', 'shift_label'], unique=False)
    op.create_table('rig_downtime_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('down_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('down_secs', sa.Float(), nullable=True),
    sa.Column('issue', sa.String(length=64), nullable=False),
    sa.Column('issue_path', sa.Text(), nullable=True),
    sa.Column('needs_manager', sa.Boolean(), nullable=False),
    sa.Column('charged_to', sa.String(length=24), nullable=False),
    sa.Column('source_event', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_downtime_open', 'rig_downtime_events', ['rig_id', 'up_at'], unique=False)
    op.create_index('ix_downtime_rig_shift', 'rig_downtime_events', ['rig_id', 'shift_date', 'shift_label'], unique=False)
    op.create_table('rig_productivity_blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.Column('recorded_secs', sa.Float(), nullable=False),
    sa.Column('assigned_secs', sa.Float(), nullable=False),
    sa.Column('fault_secs', sa.Float(), nullable=False),
    sa.Column('down_secs', sa.Float(), nullable=False),
    sa.Column('source_event', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event', name='uq_blocks_source_event')
    )
    op.create_index('ix_blocks_operator_shift', 'rig_productivity_blocks', ['operator_id', 'shift_date', 'shift_label'], unique=False)
    op.create_table('rig_shift_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('subsystem', sa.String(length=32), nullable=True),
    sa.Column('seconds_charged', sa.Float(), nullable=False),
    sa.Column('source_event', sa.BigInteger(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_checks_rig_shift', 'rig_shift_checks', ['rig_id', 'shift_date', 'shift_label'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rig_id', sa.String(length=16), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.String(length=16), nullable=False),
    sa.Column('turn_from', sa.String(length=5), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by', sa.String(length=16), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rig_id', 'shift_date', 'shift_label', 'turn_from', 'operator_id', name='uq_sessions_turn')
    )
    op.create_index('ix_sessions_operator', 'sessions', ['operator_id', 'shift_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_operator', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_shift_checks_rig_shift', table_name='rig_shift_checks')
    op.drop_table('rig_shift_checks')
    op.drop_index('ix_blocks_operator_shift', table_name='rig_productivity_blocks')
    op.drop_table('rig_productivity_blocks')
    op.drop_index('ix_downtime_rig_shift', table_name='rig_downtime_events')
    op.drop_index('ix_downtime_open', table_name='rig_downtime_events')
    op.drop_table('rig_downtime_events')
    op.drop_index('ix_episodes_rig_shift', table_name='episodes')
    op.drop_index('ix_episodes_operator', table_name='episodes')
    op.drop_table('episodes')
    # ### end Alembic commands ###
