"""how a downtime ended

Only rig_up ever closed an outage, and there are ordinary ways for it
never to arrive: the operator ends their session with the rig still down,
a technician fixes it, and the rig comes back with no memory of the
outage. The row stayed open for ever, and the floor board showed a
working rig as down with the duration climbing. That is the alert a
manager is most likely to act on, and one that never clears teaches
people to ignore the rest of them.

An outage now also closes when the rig demonstrably goes back to work.
`ended_by` says which happened, because the two are not the same number:
an operator close carries what the rig counted frame by frame, and a
resumed close carries an upper bound - it was fixed at some point at or
before that work.

Existing rows keep a null `ended_by`. That is honest rather than a
backfill: nobody knows how they ended, and guessing "operator" would
claim a measurement that was never taken.

Revision ID: e8a71c919b40
Revises: f5e889eb5ff6
"""
from alembic import op
import sqlalchemy as sa


revision = 'e8a71c919b40'
down_revision = 'f5e889eb5ff6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rig_downtime_events', sa.Column('ended_by', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rig_downtime_events', 'ended_by')
    # ### end Alembic commands ###
