"""one fact per ledger row

`rig_productivity_blocks` has always carried a unique constraint on
`source_event`, with a comment explaining why: replaying the ledger must
not double a fact, and that is made true at the database rather than in
the worker. The reasoning applies identically to shift checks and
downtime events, and it had only ever been applied to one of the three.

It became load-bearing with the projection claim taking a row lock.
Before that, two workers reading the same tail collided on the episode
primary key or the sessions constraint and the whole batch rolled back -
harmless by accident. A batch of nothing but shift checks against a
session that already exists had nothing to collide with, and silently
doubled. Doubled shift checks inflate fault counts, and fault counts are
what `repeat_fault` alerts on.

Any duplicates already present are collapsed first, keeping the lowest
id. There should be none - the projection has only ever run single-file -
but a constraint that cannot be created because of data it exists to
prevent is a bad way to find that out at three in the morning.

Revision ID: f5e889eb5ff6
Revises: 4475469fc762
"""
from alembic import op
import sqlalchemy as sa


revision = 'f5e889eb5ff6'
down_revision = '4475469fc762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    for table in ("rig_shift_checks", "rig_downtime_events"):
        op.execute(sa.text(
            "DELETE FROM %s a USING %s b "
            "WHERE a.source_event = b.source_event AND a.id > b.id" % (table, table)
        ))

    op.create_unique_constraint('uq_downtime_source_event', 'rig_downtime_events', ['source_event'])
    op.create_unique_constraint('uq_shift_checks_source_event', 'rig_shift_checks', ['source_event'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shift_checks_source_event', 'rig_shift_checks', type_='unique')
    op.drop_constraint('uq_downtime_source_event', 'rig_downtime_events', type_='unique')
    # ### end Alembic commands ###
